# golangci-lint configuration for mail-reflector
# Updated to modern version while maintaining enable-all philosophy

version = 2

[run]
timeout = "5m"
tests = true
go = "1.23"

[output]
format = "colored-line-number"
print-issued-lines = true
print-linter-name = true
sort-results = true

[issues]
max-issues-per-linter = 0
max-same-issues = 0

[[issues.exclude-rules]]
# no longer a problem in go 1.22+
linters = ["gosec"]
text = "G601:"

[[issues.exclude-rules]]
# safe to ignore - viper binding patterns
linters = ["errcheck"]
source = "viper.BindPFlag"

[[issues.exclude-rules]]
# not a magic number in CLI contexts
linters = ["mnd", "gomnd"]
source = "cobra.MinimumNArgs"

[[issues.exclude-rules]]
# idiomatic cobra/viper usage in CLI commands
path = "cmd/.*\\.go"
linters = ["gochecknoinits", "gochecknoglobals"]

[[issues.exclude-rules]]
# errors are not consumed in CLI layer - acceptable pattern
path = "cmd/.*\\.go"
linters = ["err113", "goerr113", "wrapcheck"]

[[issues.exclude-rules]]
# web interface specific relaxations
path = "internal/web/.*\\.go"
linters = ["gosec", "varnamelen", "forbidigo", "godot"]

[[issues.exclude-rules]]
# hardcoded credentials acceptable in auth.go for Sprint 1.1 (will be fixed in Sprint 4.1)
path = "internal/web/auth\\.go"
linters = ["gosec"]
text = "G101"

[[issues.exclude-rules]]
# test files should be less strict
path = "_test\\.go"
linters = ["funlen", "gocyclo", "dupl", "gosec", "varnamelen"]

# Severity configuration removed for compatibility

[linters]
# enable all linters by default and selectively disable problematic ones
enable-all = true
disable = [
  # Too restrictive for this project
  "depguard",       # module restrictions not needed
  "ireturn",        # interface returns are fine
  "nonamedreturns", # named returns are useful in some contexts
  
  # Style preferences (handled by treefmt)
  "nlreturn",       # covered by wsl
  
  # Not needed for this project type
  "exhaustruct",    # struct initialization can be partial
  "wrapcheck",      # error wrapping not always needed in CLI
]

[linters-settings]
[linters-settings.wsl]
allow-cuddle-declarations = true
allow-trailing-comment = true
force-case-trailing-whitespace = 0

[linters-settings.varnamelen]
ignore-names = ["rx", "tx", "db", "ok", "mw", "gw", "rt", "id", "mx", "w", "r"]
ignore-decls = [
  "w http.ResponseWriter", 
  "r *http.Request", 
  "g *Gateway",
  "s *Server",
  "a *AuthManager"
]

[linters-settings.tagliatelle.case.rules]
json = "snake"
envconfig = "upperSnake"

[linters-settings.gci]
local-prefixes = "github.com/meko-christian/mail-reflector"

[linters-settings.govet]
enable-all = true
disable = ["fieldalignment"]  # too pedantic for this project

[linters-settings.revive]
min-confidence = 0.8

[linters-settings.gomnd]
ignored-numbers = ["2", "3", "4", "5", "10", "24", "60", "100", "1000"]
ignored-files = ["_test.go"]
ignored-functions = ["make", "cobra.MinimumNArgs"]

[linters-settings.funlen]
lines = 120
statements = 60

[linters-settings.cyclop]
max-complexity = 15

[linters-settings.gocognit]
min-complexity = 20

[linters-settings.lll]
line-length = 120

[linters-settings.maligned]
suggest-new = true

[linters-settings.misspell]
locale = "US"
