name: Build and Upload Release Binaries

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Build binaries for release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p dist
          EXT=""
          if [ "${GOOS}" == "windows" ]; then EXT=".exe"; fi
          VERSION=${{ github.event.release.tag_name }}
          go build -o dist/mail-reflector-${GOOS}-${GOARCH}${EXT} -ldflags "-X mail-reflector/cmd.Version=$VERSION"

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/mail-reflector-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}